numero_inteiro = int(input("Dê UM NUMERO ->"))
DOBRO_do_INTEIRO = int(input(numero_inteiro * 2))
variavel_2 = int(input("Dẽ a variavel 2" ))
print(variavel_2 * variavel_2)
idade = int(input("Mostre a idade -> "))
print(idade * 12)
print(idade * 365)
numero_1 = int(input("Dê o primeiro número ->"))
numero_2 = int(input("Dê o segundo número ->"))
numero_3 = int(input("Dê o terceiro número ->"))
media =((numero_1 + numero_2 + numero_3) / 3 )
print("A média dos trê é ->" , media)
print(type(media))